Test feature fixes #1
savak1990/TestRepository pull request #2
Opened 2020-01-25 13:09 UTC by vklyovan

Test feature

2020-01-25 13:13 UTC, savak1990 requested changes
Hey, good job!

2020-01-25 13:13 UTC, savak1990 commented on lib/main.dart
> +        tooltip: 'Change counter',
Please revert this part

2020-01-25 13:15 UTC, vklyovan commented
Please merge with master branch first

2020-01-26 08:00 UTC, savak1990 approved these changes

2020-01-26 08:01 UTC, merged